name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: ["mavric-team"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what should have happened!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure adapter with '...'
        2. Call method '....'
        3. See error
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Minimal Code Sample
      description: If applicable, add a minimal code sample to help explain your problem.
      render: typescript
      placeholder: |
        import { apsoAdapter } from '@apso/better-auth-apso-adapter';
        
        const adapter = apsoAdapter({
          baseUrl: 'http://localhost:3000',
          // ... configuration
        });

  - type: dropdown
    id: version
    attributes:
      label: Package Version
      description: What version of the package are you using?
      options:
        - "Latest"
        - "0.1.0"
        - "Other (please specify in additional context)"
    validations:
      required: true

  - type: input
    id: better-auth-version
    attributes:
      label: Better Auth Version
      description: What version of Better Auth are you using?
      placeholder: "1.3.0"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running this in?
      options:
        - "Node.js"
        - "Browser"
        - "Both"
        - "Other (please specify)"
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version (if applicable)
      description: What version of Node.js are you using?
      placeholder: "20.12.0"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the problem here. This could include:
        - Error messages or stack traces
        - Network requests/responses
        - Configuration details
        - Screenshots
      placeholder: Add any additional context here...

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true