import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConfigModule } from '@nestjs/config';

// Generated by Apso CLI - these imports will be auto-generated
// import { UserModule } from './user/user.module';
// import { SessionModule } from './session/session.module';
// import { VerificationTokenModule } from './verification-token/verification-token.module';
// import { AccountModule } from './account/account.module';

@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
    }),
    TypeOrmModule.forRoot({
      type: 'postgres',
      host: process.env.DB_HOST || 'localhost',
      port: parseInt(process.env.DB_PORT, 10) || 5432,
      username: process.env.DB_USERNAME || 'postgres',
      password: process.env.DB_PASSWORD || 'password',
      database: process.env.DB_DATABASE || 'better_auth_example',
      entities: [__dirname + '/**/*.entity{.ts,.js}'],
      synchronize: process.env.NODE_ENV !== 'production', // Only for development
      logging: process.env.NODE_ENV === 'development',
    }),
    // Auto-generated modules will be added here by Apso CLI
    // UserModule,
    // SessionModule,
    // VerificationTokenModule,
    // AccountModule,
  ],
  controllers: [],
  providers: [],
})
export class AppModule {}